title: Mai Tran
logo: "/assets/img/Profile Pic.jpg?raw=true"
description: >I am a certified data analyst who is curiosity-driven for knowledge. Here are some of the analyses that I like to share.
theme: jekyll-theme-minimal
