title: Mai Tran
logo: "/assets/img/Profile Pic.jpg?raw=true"
description: > 
  I used to be a teacher who was always curious about the causes behind human beings' behaviors and matters.
  <br><br>
  Now I've finally found a way to fulfill that inquisitive mind in data analytics. Data analyzing and teaching have a lot in common, only differ in who the stakeholders are.
  <br><br>
theme: jekyll-theme-minimal
